### ISSUE TITLE
"Settings" shouldn't be available if `allowAdminChanges` is disabled

### ISSUE THREAD

**Issue by lindseydiloreto** [solspace/craft-express-forms#11]
In following Craft's new Project Config standards, it should be impossible to access the "Settings" page when `allowAdminChanges` is disabled.

I just tried updating the Template Directory Path (per #8) and it kicked up an "Internal Server" error.

**Comment by kjmartens** [comment]
Thanks, we'll check into this one. :)

**Comment by kjmartens** [comment]
Fixed in v1.0.0-beta.5 now :)

**Comment by lindseydiloreto** [comment]
Sweet! 🙂
