### ISSUE TITLE
Form submission not clickable in admin

### ISSUE THREAD

**Issue by gracehcoote** [solspace/craft-express-forms#115]
**Describe the bug or issue you're experiencing**
I have noticed this problem since upgrading to Craft 4, but can't confirm that's the cause. Basically, when a submission is made via the form, it appears in the admin and can usually be clicked to view in full. The link for this is usually the "Title" field. However, this is no longer visible in the admin meaning I can't click to open submissions.

**Steps to reproduce**
For the purposes of making sure it wasn't something I was doing wrong, I installed the Express Form demo and tested with that, result was the same.

1. Make a form submission
2. Go to Submissions in admin
3. Submissions in table has no link
4. Customising the source of the table in Craft 3 shows a faded out Title field - this does not appear in the Craft 4 admin version. Title field is there, but can be disabled or moved, and when enabled it is not a link.

**Expected behavior**
Title of each form submission should be a clickable link.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.3.6.1
- Express Forms Version: 2.0.1
- Express Forms Edition: Lite
- Fresh Install or Upgrade: Fresh install

**Additional context**

**Comment by kjmartens** [comment]
I'm very sorry for the trouble and the delay @gracehcoote. We'll get this corrected shortly. 🙂

**Comment by kjmartens** [comment]
This is now resolved in Express Forms 2.0.2. 🙂
