### ISSUE TITLE
cannot dublicate form

### ISSUE THREAD

**Issue by krizzzly** [solspace/craft-express-forms#117]
When duplicating a form it throws an error. Afterwards the form shows up, but fields are empty.

Craft: 4.3.8.2
Express Forms: 2.0.1

**Comment by kjmartens** [comment]
Sorry for the delay @krizzzly. 

In my testing, using the duplicate button on the forms list seems to correctly duplicate the form. However, if I try to "save as a new form" inside the form builder, that appears to do nothing.

Is this what is happening for you as well? 🙂

**Comment by kjmartens** [comment]
This is now resolved in Express Forms 2.0.2. 🙂
