### ISSUE TITLE
Express-Forms Submissions Error when Freeform is installed

### ISSUE THREAD

**Issue by krizzzly** [solspace/craft-express-forms#118]
If both plugins are installed on Craft v4 and latest versions of Express-Forms and Freeform, clicking on submissions in Express-Forms throws an error.

**Comment by kjmartens** [comment]
Sorry for the delay @krizzzly.

In my testing, I cannot duplicate this specific issue, but I can see that the submission title links to view individual submissions are not showing. We'll get that fixed shortly.

**Comment by kjmartens** [comment]
Can you see if this issue is still happening for you in Express Forms 2.0.2? 🙂
