### ISSUE TITLE
Error using PostgreSQL database

### ISSUE THREAD

**Issue by putyourlightson** [solspace/craft-express-forms#12]
### Description

I'm getting an error when trying to create a new form and suspect it is because of the PostgreSQL database.

### Steps to reproduce

1. Install plugin.
2. Try to save a new form.

### Additional info

- Express Forms edition & version: 1.0.0-beta.5 PRO
- Craft version: 3.1.24
- Database driver & version: PostgreSQL 11 Apline

---

Full error:

Integrity constraint violation – yii\db\IntegrityException
SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "id" violates not-null constraint
DETAIL: Failing row contains (null, 756a1de1-e167-471e-a40a-eabdedf35590, null, Contact Form, contactForm, null, #fdc824, {{ dateCreated|date("Y-m-d H:i:s") }}, t, null, null, null, null, 0, [{"id":null,"uid":"4742d59c-3ff4-461c-abd3-65dcda1708f4","name":..., [], 0, 2019-04-29 16:25:55, 2019-04-29 16:25:55, 67bce8d4-b957-4200-8065-78ab6c302233).
The SQL being executed was: INSERT INTO "expressforms_forms" ("id", "uuid", "name", "handle", "description", "color", "submissionTitle", "saveSubmissions", "adminNotification", "adminEmails", "submitterNotification", "submitterEmailField", "fields", "integrations", "spamCount", "dateCreated", "uid", "dateUpdated") VALUES (NULL, '756a1de1-e167-471e-a40a-eabdedf35590', 'Contact Form', 'contactForm', NULL, '#fdc824', '{{ dateCreated|date("Y-m-d H:i:s") }}', TRUE, NULL, NULL, NULL, NULL, '[{"id":null,"uid":"4742d59c-3ff4-461c-abd3-65dcda1708f4","name":"Name","handle":"name","type":"text","required":false}]', '[]', 0, '2019-04-29 16:25:55', '67bce8d4-b957-4200-8065-78ab6c302233', '2019-04-29 16:25:55') RETURNING "id"

![Screenshot 2019-04-29 at 18 26 43](https://user-images.githubusercontent.com/2318222/56911465-40c43e00-6aad-11e9-8151-1fc2eb5af2a1.png)

**Comment by kjmartens** [comment]
Sorry for the trouble Ben, and thanks for reporting this. I'll have our developer check into this, and we'll likely have a fix by tomorrow morning. 🙂

**Comment by putyourlightson** [comment]
Thanks Kelsey!

**Comment by kjmartens** [comment]
Hi Ben, can you try out v1.0.0-beta.6 and see if it resolves the issue for you? :)

**Comment by putyourlightson** [comment]
Resolved, thank you!

![Screenshot 2019-04-30 at 18 18 09](https://user-images.githubusercontent.com/2318222/56976935-5c464c00-6b74-11e9-81b0-974f576e48f1.png)
