### ISSUE TITLE
Submissions not working Craft 4 upgrade

### ISSUE THREAD

**Issue by clarknelson** [solspace/craft-express-forms#124]
**Describe the bug or issue you're experiencing**

I upgraded craft and express forms to the latest versions, now my contact form won't track submissions. 

Everything looks okay on the front-end, I double checked that everything matched the recommended syntax in the docs. The only thing is when I go to submissions theres nothing there. I tried duplicating the form as well but no luck at all. Any ideas where to turn? No console messages, etc.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.8.2
- Express Forms Version: 2.0.3
- Express Forms Edition: Lite
- Fresh Install or Upgrade: Upgrade

**Additional context**

I can email database / logs if needed.

Thank you!

**Comment by kjmartens** [comment]
Hi @clarknelson,

What do you mean by "won't track submissions"? Won't save the submission data to the database, or won't send email notifications? 🙂 

What does your email notification template look like? If you're using the old way of grabbing the system email address and name, you'll need to update that to use the `projectConfig` approach instead:

``` twig
fromName: '{{ craft.app.projectConfig.get("email.fromName") }}'
fromEmail: '{{ craft.app.projectConfig.get("email.fromEmail") }}'
```

**Comment by clarknelson** [comment]
This is what the current notification template looks like: 

![CleanShot 2024-03-16 at 22 35 36@2x](https://github.com/solspace/craft-express-forms/assets/4106671/92518648-1565-4ebd-9fdf-ba2fe8a51356)

I tried to update to the suggested syntax but there's still no submissions appearing in the dashboard:

![CleanShot 2024-03-16 at 22 39 40@2x](https://github.com/solspace/craft-express-forms/assets/4106671/2369c012-5aa5-4026-b363-d7705922b416)

Here's the whole form if you think there might be a syntax issue:

```

		{% if form.submittedSuccessfully %}
			<div class="success message">Thanks for getting in touch!</div>
		{% endif %}

		{% if not form.valid %}
			<div class="failure message">
				Sorry, there was an error.
				{% if form.errors|length %}
					<ul>
						{% for error in form.errors %}
							<li>{{ error|t }}</li>
						{% endfor %}
					</ul>
				{% endif %}
			</div>
		{% endif %}

		{{ form.openTag({
			attributes: {
				id: 'ajax-form',
			},
            return: '/#contact-form',
            template: '_notifications/admin.twig'
        }) }}

		<div class="row">
			<input type="text" name="firstName" placeholder="First Name*" value="{{ form.fields.firstName.value }}" required/>
			{{ forms.renderErrors(form.fields.firstName) }}
			<input type="text" name="lastName" placeholder="Last Name*" value="{{ form.fields.lastName.value }}" required/>
			{{ forms.renderErrors(form.fields.lastName) }}
		</div>
		<input type="email" name="email" placeholder="E-mail*" value="{{ form.fields.email.value }}" required/>
		{{ forms.renderErrors(form.fields.email) }}
		<input type="text" name="subject" placeholder="Subject*" value="{{ form.fields.subject.value }}" required/>
		{{ forms.renderErrors(form.fields.subject) }}
		<textarea type="text" name="message" placeholder="I dream of marshmallows..." rows="5">{{ form.fields.message.value }}</textarea>
		{{ forms.renderErrors(form.fields.message) }}
		{# {{ form.recaptcha.render }} #}

		{# {{ forms.renderErrors(form.recaptcha) }} #}
		<button class="button submit" type="submit">Submit</button>

		{# Form Contents #}
		{{ form.closeTag }}

		{% include "includes/_formAjax" %}
		```

**Comment by eheiser** [comment]
I have exactly the same issue. I'll be replacing it by Freeform pro asap.
