### ISSUE TITLE
Allow templates to use ENV vars for email and from name etc

### ISSUE THREAD

**Issue by terryupton** [solspace/craft-express-forms#15]
### Description
Currently I set all my email settings via ENV vars. 
```
EMAIL_FROM_ADDRESS = "email@email.com"
EMAIL_FROM_NAME = "Company Name"
```

So when I use the following in templates:
```
fromName: '{{ craft.app.systemSettings.getSettings("email").fromName }}'
fromEmail: '{{ craft.app.systemSettings.getSettings("email").fromEmail }}'
replyTo: '{{ craft.app.systemSettings.getSettings("email").fromEmail }}'
```

It falls over with the following errors:
```
Email notification [template.twig]: Address in mailbox given [$EMAIL_FROM_ADDRESS] does not comply with RFC 2822, 3.6.2. [] []
```
Would it be possible to use ENV vars.

### Additional info

- Express Forms edition & version: 1.0.0-beta.6
- Craft version: Craft Pro 3.1.25

**Comment by kjmartens** [comment]
Thanks @terryupton. I'll check with our developer and see if this is an easy add on our end. 🙂

**Comment by kjmartens** [comment]
We'll add support for this in the next version of Express Forms 🙂

**Comment by kjmartens** [comment]
This is fixed now in v1.0.0.

Just to clarify, you need to specifically use the environment variable directly inside the notification templates, e.g. `$EMAIL_FROM_ADDRESS` (rather than specifying `{{ craft.app.systemSettings.getSettings("email").email }}` etc). :)

**Comment by terryupton** [comment]
Thanks for this @kjmartens - is this a fix you could also introduce to the normal FreeForm Pro and Lite?

**Comment by kjmartens** [comment]
@terryupton Yes, it's on our list for the next version. :)

**Comment by terryupton** [comment]
Hi @kjmartens - Sorry I lost track of this. Is this still waiting to be rolled out for FreeForm Pro and Lite or was this fixed? I didn't see a mention in the Pro change-log so wasn't sure, but then I had thought i'd seen it mentioned somewhere else?

**Comment by kjmartens** [comment]
@terryupton It's already done internally, but it's tied up with many other large changes. We're getting much closer to our next big update of Freeform which will include this. Perhaps a week or two away.

**Comment by terryupton** [comment]
No worries @kjmartens - wasn't sure if I had just overlooked it.
