### ISSUE TITLE
Recaptcha documentation improvement

### ISSUE THREAD

**Issue by WHITE-developer** [solspace/craft-express-forms#20]
No bug this time, but just something I was missing in the docs.

When disabling the recaptcha `Load script` setting and adding the recaptcha script manually (for example to change the language of it) you also need to add `recaptcha: true` to your `form.openTag` to get the backend validation of the recaptcha working. 

Took me an hour to debug and find out :wink:

**Comment by kjmartens** [comment]
Sorry about that! We'll make an update to the docs this week. :)
