### ISSUE TITLE
Case sensitivity issue in class namespace

### ISSUE THREAD

**Issue by Mosnar** [solspace/craft-express-forms#25]
### Description
On our AWS production environment, I'm getting the following error on the dashboard:
```
Error: Class 'Solspace\ExpressForms\Services\Widgets' not found in /var/app/current/vendor/solspace/craft-express-forms/src/widgets/OverviewStatsWidget.php:83
```

The reason for this is because the folder name `services` does not match the `OverviewStatsWidget` class' namespace `Services` (Notice the capital S)

For most people this isn't an issue, but for us it causes a fatal error.

### Additional info

- Express Forms edition & version: 1.0.4 (Pro Trial)
- Craft version: 3.3.9
- PHP version: 7.2
- Database driver & version: MySQL 5.7

**Comment by Mosnar** [comment]
Looks like this might be in two places - 
`src/services/Widgets.php`
`widgets/OverviewStatsWidget.php`

**Comment by kjmartens** [comment]
Sorry for the delay, and thanks for reporting this. We'll check into this and get it resolved soon. :)

**Comment by kjmartens** [comment]
This will be sorted out in Express Forms 1.0.5, available this week. Sorry again for the delay.
