### ISSUE TITLE
Admin email(s) field doesn't remove empty line

### ISSUE THREAD

**Issue by mediabeastnz** [solspace/craft-express-forms#26]
### Description
If you leave an empty line in the admin email(s) field no emails are sent as it thinks no emails are entered.

### Steps to reproduce

1. enter one email address into admin field and add a extra line with no email
2. send and wait for error
3. error is rfc issue

### Additional info

- Express Forms edition & version: 1.0.4
- Craft version: 3.3
- PHP version: 7.3

**Comment by kjmartens** [comment]
@mediabeastnz Thanks for this, and sorry for the delay. We're checking into it now. :)
