### ISSUE TITLE
Deleted submissions included on CSV Exports

### ISSUE THREAD

**Issue by mynameisphil** [solspace/craft-express-forms#28]
### Description

Deleted submissions still exist on CSV exports.

### Steps to reproduce

1. Delete any number of submissions from a form
2. Export submissions as CSV (includes all submissions, including all previously deleted ones)

### Additional info

- Express Forms edition & version: Lite 1.0.4
- Craft version: Craft Pro 3.3.20.1
- PHP version: 7.2.26
- Database driver & version: MySQL 10.2.30

**Comment by kjmartens** [comment]
This will be resolved in Express Forms 1.0.6, available today. :)
