### ISSUE TITLE
Cannot access error logs if admin changes are set to false

### ISSUE THREAD

**Issue by terryupton** [solspace/craft-express-forms#30]
### Description
Unable to access error logs in live environment. I get the following errors:
 
<img width="546" alt="Screenshot 2020-02-15 at 08 52 54" src="https://user-images.githubusercontent.com/5698596/74585074-c8ddea80-4fd0-11ea-963c-7669347332f8.png">
<img width="1438" alt="Screenshot 2020-02-15 at 08 53 04" src="https://user-images.githubusercontent.com/5698596/74585075-cb404480-4fd0-11ea-96c5-b9bbb64f9670.png">

I believe this is down to the general environment setting of allowAdminChanges being set to false.
The URL for the logs is at /cms/express-forms/settings/error-log/

Naturally, errors might occur in any environment and should be accessible from anywhere to view, regardless of admin changes setting.

### Additional info

- Express Forms edition & version: 1.0.4
- Craft version: Craft Pro 3.3.18.3
- PHP version: 7.2.27

**Comment by kjmartens** [comment]
@terryupton Thanks for reporting this, and sorry for the long delay. We're working through a bunch of bug fixes for Express Forms this week, and this will be added to the list. :)

**Comment by kjmartens** [comment]
This is now fixed in Express Forms v1.0.7 🙂
