### ISSUE TITLE
Required checkboxes always throw validation error

### ISSUE THREAD

**Issue by chasegiunta** [solspace/craft-express-forms#32]
### Description
Checking a required checkbox with a form does not pass validation. The form will always return a validation error.

### Steps to reproduce

1. Create form.
2. Add simple checkbox field, eg. `acceptTerms`, mark as required
3. Template out on frontend as usual
4. Test form by checking field and submitting
5. Observe validation error

### Additional info

- Express Forms edition & version: 1.0.5
- Craft version: 3.4.19.1
- PHP version: 7.3.13

**Comment by kjmartens** [comment]
Hi @chasegiunta. Sorry for the delay... I'm not sure if this is still not working for you, but I cannot duplicate this in my own testing. In fact, the demo included with Express Forms contains an Accept Terms field exactly as you describe, and that works fine as well.

Are you able to elaborate on this if it's still and issue for you? Perhaps include template code, etc. :)

**Comment by chasegiunta** [comment]
Hi @kjmartens. It's been too long. To be honest, I can't even remember what project I was attempting to use Express Forms on. I think we ended up going a different route because of this issue. Hopefully it was something quirky on my end.

**Comment by kjmartens** [comment]
Sorry again for the delay on this.
