### ISSUE TITLE
Using "title" as a field handle causes a bug on submissions edit page in CP

### ISSUE THREAD

**Issue by thisisjamessmith** [solspace/craft-express-forms#33]
### Description

Not sure if there might be other ramifications to using this as a handle - perhaps 'title' should be reserved?

### Steps to reproduce

1. Create a form with a field with the handle 'title'. Mine was an 'options' type, used for selecting 'Mr/Mrs/Miss/Dr' etc from a select list - I haven't tested with a plain text field.
2. Make a submission
3. Try to view the submission edit screen in the CP and see error message:

`Argument 1 passed to Solspace\ExpressForms\fields\Options::getValueDictionaryFromValues() must be of the type array, string given, called in /vendor/twig/twig/src/Extension/CoreExtension.php on line 1499`

### Additional info

- Express Forms edition & version: Lite 1.0.5
- Craft version: 3.4
- PHP version: 7.1

**Comment by kjmartens** [comment]
@thisisjamessmith Thanks for this, and sorry for the delay. We're working through a bunch of Express Forms bugs this week and this will be added to that. :)

**Comment by gustavs-gutmanis** [comment]
@thisisjamessmith we've implemented a fix that prevents the error from being thrown and displays the submission correctly, which will be released in the next version.

However if you're using the `<select>` input for choosing one of the options or if you're using a radio field, you should choose the `Text` type in the form settings, becuase `Options` type is meant for multiple value fields like checkbox and multi-select.

**Comment by kjmartens** [comment]
This is now fixed in Express Forms v1.0.7 🙂
