### ISSUE TITLE
Outputting field values in email notifications only works if I prefix them with `submission.`

### ISSUE THREAD

**Issue by thisisjamessmith** [solspace/craft-express-forms#34]
The docs suggest that you can output field values in a notification email simply using their field handle. For some reason this doesn't work for me - I need to prefix them with `{{ submission.fieldHandle }}`.

**Comment by kjmartens** [comment]
Sorry for the delay @thisisjamessmith. The correct syntax expected for email notification would be `{fieldHandle}`, not `{{ fieldHandle }}`. I tested this again now and it seems to work fine for me. I'll check with a developer though, and see if there's any reason why `{{ fieldHandle }}` syntax shouldn't/couldn't work. :)

**Comment by kjmartens** [comment]
I've just confirmed this is expected behavior, and there's no ability to have `{{ fieldHandle }}` syntax work. It must either be  `{fieldHandle}` or `{{ submission.fieldHandle }}`. :)
