### ISSUE TITLE
Upgrade path to Freeform pro

### ISSUE THREAD

**Issue by sm-md-lg** [solspace/craft-express-forms#36]
Is there an upgrade path from Express Forms to Freeform Pro?

From looking at the docs it looks like an upgrade can only be from the free version to Express Pro.  If there is not a built in way, could it be done with a custom module or by using SQL directly?

**Comment by kjmartens** [comment]
Currently, there is no upgrade path available, but we will likely have a migration ready for Freeform 4 in a few months time. :)

In the meantime, you may be able to build a custom module to achieve this, but we can't provide any assistance with that unfortunately.

**Comment by sm-md-lg** [comment]
So just to be clear, there will eventually be a path from the free version up through all four versions to Freeform pro?

Our thinking is that with Express Forms, we can now install that by default with all our clients and we will be able to say that if you need increased functionality, there is a path from the free version all the way to Freeform Pro.

**Comment by kjmartens** [comment]
The plan would be for us to have a migration utility built into Freeform 4 that allows you to migrate from Express Forms and possibly some other form plugins. 😉 

To be clear, this would be a Freeform 4 only thing, and this migrator would only be available from Express Forms -> Freeform 4, or Form Plugin X -> Freeform 4, etc.

**Comment by sm-md-lg** [comment]
Awesome, this is great to see.

**Comment by kjmartens** [comment]
Yes, when we first built Express Forms (XF), this was the larger picture idea we had. Customers could load up XF to begin/as default, and then scale up to Freeform Lite or Pro whenever they needed to, as there became more and more features needed for the site. :)
