### ISSUE TITLE
Add ReCaptcha theme option (light/dark)

### ISSUE THREAD

**Issue by thijskaspers** [solspace/craft-express-forms#39]
Google has two theme options to render a ReCaptcha checkbox field, a light and dark version. The light version isn't looking very good on dark backgrounds, but that is the one that Express Forms uses by default.

You can see the options here: https://developers.google.com/recaptcha/docs/display

Would be nice if there's an easy way to change the theme that Express Forms uses when rendering the field.

**Comment by kjmartens** [comment]
@thijskaspers Thanks for your feedback. We'll add support for this, as well as display size in an upcoming version of XF. :)

**Comment by kjmartens** [comment]
This is now added in Express Forms v1.0.7 🙂
