### ISSUE TITLE
RFC 2822, 3.6.2

### ISSUE THREAD

**Issue by Djive** [solspace/craft-express-forms#41]
### Description

Email notification [admin-notification.twig]: Address in mailbox given [] does not comply with RFC 2822, 3.6.2. [] []

I get these in logs... tryes to call admin email in notification templates on different ways suggested on other tickets..
But still

### Additional info

Latest version of both

**Comment by kjmartens** [comment]
@Djive Sorry for the delay. Can you elaborate on what your setup is like? Are you using the Admin Notification feature here, what does your notification template look like, etc? :)

**Comment by Djive** [comment]
Sorry for delay > dev was on holliday :)
we upgraded to last version... and tryed all seetings we foud here in prevoius issues
 but still seems some issues..not gettign email.. 
here is couple images.. if you can help.
![form2](https://user-images.githubusercontent.com/1241189/96897378-d2d4b900-148e-11eb-99aa-4566e0d5c250.png)
![form1](https://user-images.githubusercontent.com/1241189/96897381-d405e600-148e-11eb-985f-382f9720b7e4.png)
![form3](https://user-images.githubusercontent.com/1241189/96897384-d405e600-148e-11eb-8136-7995cf31d116.png)

**Comment by kjmartens** [comment]
@Djive sorry again for the delay... I can see in your screenshot you have `eMail` for your Email field handle, and are using `email` in your notification template. If that's not the issue, it might simply be that the Admin Emails setting inside the form builder currently does not support the use of ENV vars. Can you try changing it to something else and confirm if the email goes through? :)
