### ISSUE TITLE
Submit Controller should respond not respond with json when the Accept: application/json header is not set

### ISSUE THREAD

**Issue by leevigraham** [solspace/craft-express-forms#42]
### Description

https://github.com/solspace/craft-express-forms/blob/master/src/controllers/SubmitController.php#L57 is checking for an ajax request, not `Accept` headers

### Steps to reproduce

1. Submit an ajax request without the `Accepts: application/json` header
2. JSON is returned, not HTML

**Comment by kjmartens** [comment]
@leevigraham Sorry for the delay. We'll check into this shortly :)

**Comment by kjmartens** [comment]
This is now added in Express Forms v1.0.7 🙂
