### ISSUE TITLE
Error style in Head

### ISSUE THREAD

**Issue by thefubon** [solspace/craft-express-forms#43]
### Description
I have a problem with a file that is sent to the user after clicking the submit button. If I use this code, an email is not sent to me or it gives an error. How to correctly add styles to the file without referencing the style?

<img width="1172" alt="Снимок экрана 2020-09-29 в 22 06 18" src="https://user-images.githubusercontent.com/43171309/94604223-05c8ca00-02a0-11eb-8f9d-8048aa6be16a.png">

### Additional info

- Express Forms edition & version: 1.0.6 Free
- Craft version: 3.5.11.1
- PHP version: 7.2.32
- Database driver & version: MySQL 5.7.30

**Comment by kjmartens** [comment]
@thefubon Would you be able to elaborate on what you're trying to do and what the issue is here? We're having a hard time trying to understand this one. Thanks! :)
