### ISSUE TITLE
Spam emails are sent when using dynamic notifications

### ISSUE THREAD

**Issue by CMeldgaard** [solspace/craft-express-forms#44]
### Description
When using dynamic notifications, spam emails are still sent to the recipients.

The ```DynamicNotificationsDecorator::sendEmails()``` method does not check whether ```$form->isMarkedAsSpam()``` is true, but emails all submissions regardless of their spam status.

### Steps to reproduce
Enable honeypot spam protection on a form with dynamic notifications
Submit the form with a non-empty honeypot field
See that the submission has been blocked in the control panel, but the spam email has still been sent to the dynamic notification address

### Additional info
Express Forms edition & version: Lite 1.0.6
Craft version: 3.5.3
PHP version: 7.3

**Comment by kjmartens** [comment]
@CMeldgaard Thanks, we'll check into this shortly. :)

**Comment by kjmartens** [comment]
This is now fixed in Express Forms v1.0.7 🙂
