### ISSUE TITLE
Emails end up in spam

### ISSUE THREAD

**Issue by thefubon** [solspace/craft-express-forms#47]
### Description

Please tell me how to get rid of the letter getting into spam. All letters sent to different mailing addresses end up in spam. The same is in the plugin freeform

https://craft.fubon.uk/contact (freeform)
https://isignals.trade (express-forms)

Настройки сервера:
![express](https://user-images.githubusercontent.com/43171309/97198570-03cf2980-17c0-11eb-9645-ba1ce2fc3dae.jpg)

### Additional info

- Express Forms edition & version: 1.0.8
- Craft version: 3.5.14
- PHP version: 7.2.32
- Database driver & version: MySQL 5.7.30

**Comment by gustavs-gutmanis** [comment]
This is out of scope for our plugin.  
You should consult your email server administrator.
