### ISSUE TITLE
Error in docs: `craft.expressforms.form`

### ISSUE THREAD

**Issue by lindseydiloreto** [solspace/craft-express-forms#6]
On this page of the docs...

http://craft.express/forms/v1/templating/examples.html

... this line is mentioned several times:

```twig
{% set form = craft.expressforms("contact") %}
```

However, that's incorrect. It should say this:

```twig
{% set form = craft.expressforms.form("contact") %}
```

**Comment by kjmartens** [comment]
Thanks! Will fix this shortly.

**Comment by lindseydiloreto** [comment]
Great, thanks!
