### ISSUE TITLE
Error in docs: Bug in email template example

### ISSUE THREAD

**Issue by lindseydiloreto** [solspace/craft-express-forms#7]
In the docs, there is an example template for emails sent to an admin...

http://craft.express/forms/v1/overview/email-notifications.html#admin-2

Due to the use of an unescaped single quote, copy & pasting this example will immediately throw an error. Specifically, the `subject` line is problematic:

```php
subject: 'We've received your submission from the {{ form.name }} form'
```

**Comment by kjmartens** [comment]
Thanks! We'll get this corrected shortly (and make it so the single quote doesn't need to be escaped either).

**Comment by lindseydiloreto** [comment]
Awesome, thanks!

Loving the plugin so far, btw. Nice work!

**Comment by kjmartens** [comment]
We've updated the docs... Express Forms will also automatically escape single quotes when you use the CP editor instead. :)
