### ISSUE TITLE
EmailNotificationTest.php does not comply with psr-4 autoloading standard

### ISSUE THREAD

**Issue by ademers** [solspace/craft-express-forms#73]
**Describe the bug or issue you're experiencing**

When I run Composer commands from the CLI, I get error:
```
Solspace\Tests\ExpressForms\models\EmailNotificationTest located in ./vendor/solspace/craft-express-forms/packages/plugin/tests/objects/EmailNotifications/EmailNotificationTest.php does not comply with psr-4 autoloading standard.
```
My understanding is that this is related to Composer 2.

**Steps to reproduce**

1. Run a Composer command from CLI
2. See error:
```
Solspace\Tests\ExpressForms\models\EmailNotificationTest located in ./vendor/solspace/craft-express-forms/packages/plugin/tests/objects/EmailNotifications/EmailNotificationTest.php does not comply with psr-4 autoloading standard
```

**Expected behavior**

No psr-4 compliance errors.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 3.6.10 in local dev running Nitro 2.0.6 + PHP 7.4.16 + mySQL 8.0.23 + Composer 2
- Express Forms Version: 1.1.0
- Express Forms Edition: Lite
- Fresh Install or Upgrade: Fresh

**Additional context**

**Comment by lindseydiloreto** [comment]
I'm getting this too. Should be a relatively easy namespace fix, in order to keep the plugin compliant with Composer 2.

**Comment by gustavs-gutmanis** [comment]
@ademers thanks for reporting this, we'll release a fix for this shortly.
