### ISSUE TITLE
Remove `ramsey/uuid` dependency

### ISSUE THREAD

**Issue by khalwat** [solspace/craft-express-forms#74]
Probably you don't need the `ramsey/uuid` dependency at all, and can just remove the package. This is a good thing in terms of reducing dependencies to avoid situations like this:

https://github.com/percipioglobal/craft-notifications/issues/66

You can just leverage the built-in UUID generator that Craft CMS has built in:

https://github.com/craftcms/cms/blob/develop/src/helpers/StringHelper.php#L1874

It's been available since Craft CMS 3.0.0

**Comment by gustavs-gutmanis** [comment]
Thanks @khalwat!

I'll implement your suggestion shortly.
