### ISSUE TITLE
Export CSV error

### ISSUE THREAD

**Issue by DaveRayner** [solspace/craft-express-forms#78]
When we click on a forms 'Export > CSV' button on the 'Forms' index page we get an SQL error.
There is no error when we use the Export function at the bottom of a form's submissions page.

Craft Pro 3.7.14
Express Forms Lite 1.1.1

This is the error:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c.field_name' in 'field list'
The SQL being executed was: SELECT s.`id`, s.`dateCreated`, c.`title`, c.`field_name`, c.`field_email`, c.`field_message`, c.`field_dogma`
FROM `expressforms_submissions` `s`
INNER JOIN `expressforms_submissions_emailTest`c ON c.`elementId` = s.`id`
INNER JOIN `expressforms_forms` `f` ON f.`id` = s.`formId`
INNER JOIN `elements` `e` ON e.`id` = s.`id` AND e.`dateDeleted` IS NULL
WHERE (s.`formId`=6) AND (c.`siteId`=1)
Error Info: Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'c.field_name' in 'field list'
)
↵
Caused by: PDOException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c.field_name' in 'field list'
in /home/c9f9ui3ssu32/vendor/yiisoft/yii2/db/Command.php at line 1302 

Thanks.

**Comment by kjmartens** [comment]
Would you be able to provide me with a copy of your database for review? You can send it to support@solspace.com. 🙂

**Comment by kjmartens** [comment]
We can now duplicate this issue as well. It seems that a recent Craft update is causing this. We'll check into this and get a fix out probably this week.

**Comment by angelokeirsebilck** [comment]
Any updates on this?

**Comment by kjmartens** [comment]
I'm very sorry for the delay. We're going to have a developer look into this and address it early next week (Monday or Tuesday). Thank you for your patience. :)

**Comment by kjmartens** [comment]
This is now fixed in v1.1.2. 🙂
