### ISSUE TITLE
"Template Directory Path" prepends full file path

### ISSUE THREAD

**Issue by lindseydiloreto** [solspace/craft-express-forms#8]
When saving the "Template Directory Path" for Email Notifications, it automatically prepends the full path after saving...

**Before saving:**

<img width="963" alt="Ω 2019-04-24 at 12 04 59 PM" src="https://user-images.githubusercontent.com/5309692/56686734-81751f00-6689-11e9-87b3-9d115fb12a82.png">

**After saving:**

<img width="962" alt="Ω 2019-04-24 at 12 05 22 PM" src="https://user-images.githubusercontent.com/5309692/56686746-86d26980-6689-11e9-9fa5-d2d573494386.png">

Not sure if it's a bug per se, but it's definitely not expected behavior.

**Comment by kjmartens** [comment]
Thanks, this must have just started after our latest update to some validation on the URL path. I'll have our developer check into it. :)

**Comment by kjmartens** [comment]
This is now fixed in v1.0.0-beta.4 :)

**Comment by lindseydiloreto** [comment]
Looks like this is now working as expected! Thanks @kjmartens & @gustavs-gutmanis! 🍺
